#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "No arguments given, please provide the name of the latest file to be renamed"
    exit
fi

name=$1
sub=$(echo $name | cut -f 1-2 -d '.')
#echo $name
#echo $sub
if [ "$name" == $sub ]; then
    echo $name and $sub are the same, aborting.
    exit
fi
mv $name.xsc $sub.xsc
mv $name.coor $sub.coor
mv $name.vel $sub.vel
mv $sub.dcd $sub.1.dcd
catdcd -o $sub.dcd $sub.1.dcd $name.dcd

