#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo -n "Enter the number of indices: "
    read max
    echo -n "Enter the input name: "
    read input
else
    if [ -f $1 ]; then
        input="$1"
        echo -n "Enter the number of indices: "
        read max
    else
        max="$1"
        echo -n "Enter the input name: "
        read input
    fi
fi

echo -n "Enter the output name: "
read output

for i in $(eval echo {1..$max});
do
    cut -f $i -d ' ' $input >> $output
done
