#!/usr/bin/env bash
# depending on the configuration, appends line numbers or lines from a separate file

if [ -z "$1" ]; then
   echo "You doof"
   exit
fi

if [ -f "$1" ]; then
   echo "Opening file $1"
else
   echo "Still a doof"
   exit
fi

# count the number of lines in the file and iterate through this number
count=$(cat $1 | wc -l) 

for i in $(eval echo {1..$((count))} );
do 
#    read out each line in sequence and pipe it to 
#    another command that appends the line number
#    j=$(($i+1))
#    sed -n $j\p $1 | sed s/$/" $i"/ >> tmp

#    alternatively, this can be used to append each line of a file to the 
#    end of each line of another file
     append=$(sed -n $i\p colorids.txt)
     sed -n $i\p pdbids.txt | sed s/$/" $append"/ >> tmp
done
cat tmp > pdbids2.txt
rm tmp
