#!/usr/bin/env bash
# This script takes 5 ns snapshots of a given trajectory

if [[ "$1" == *.dcd ]]; then 
    frames=$(catdcd -num $1 | egrep "Total" | cut -f 3 -s -d ' ')
    echo "Dcd frames: $frames"
else 

    if [[ "$2" == *.dcd ]]; then
        frames=$(catdcd -num $2 | egrep "Total" | cut -f 3 -s -d ' ')
        echo "Dcd frames: $frames"
    else
    echo "Need a dcd file"
    exit
    fi
fi

# first check that at least 1 argument has been received
if [ -z "$1" ]; then
    echo "Please provide psf and dcd inputs. If only a trajectory file is provided the standard psf will be used"
    exit
fi

# help text
if [ $1 = "help" ]; then
    echo "This script, when provided with the psf and dcd files as arguments, takes 0.5 ns snapshots of a given trajectory and saves them as pdbs."
    exit
fi

# check if the pdb/coordinate file exists 
if [ -f $1 ]
then
    echo "$1 exists"
else
    echo "Hey buddy, $1 doesn't exist"
    exit
fi

# if one argument is provided, assume the standard psf file
if [ -z "$2" ]; then
#call VMD without a display window and build a pdb from the inputs
    /Applications/VMD\ 1.9.3.app/Contents/Resources/VMD.app/Contents/MacOS/VMD -e $tclhome/longsnap.tcl -dispdev text ../step5_assembly.xplor_ext.psf -args $1
else
    if [ -f $2 ]
    then
#call VMD without a display window and build a pdb from the inputs
        /Applications/VMD\ 1.9.3.app/Contents/Resources/VMD.app/Contents/MacOS/VMD -e $tclhome/longsnap.tcl -dispdev text $1 -args $2
    else
        echo "Hey buddy, $2 doesn't exist"
    exit
    fi
fi

#name=$(ls -t | head -1 | cut -f 1 -d '_')
#mv $name\_*.pdb ~/XylE/prody_analysis/md_snapshots
