#!/usr/bin/env bash

filter="ENERGY:"
echo "Current filter is: '$filter'"
files=*.log
out=dihedralE.txt

#if [ -z "$1" ]; then
#    echo "No arguments given, please provide the name of the log file to average filter information"
#    exit
#fi
for f in $files
do
  egrep $filter $f | cut -c 50-65 >> $out
done

sed -i -e /AT/d $out
#count=$(cat tmp | wc -l)
##steps=$(egrep "TCL: Running" $1 | cut -f 4 -d ' ')
#
#sum=0
#for i in $(eval echo {1..$count});
#do
#    add=$(sed -n $i\p tmp)
#    sum=$(echo "$sum + $add" | bc)
#done
#avg=$(echo "$sum / $count" | bc -l)
##ns=$(echo "$avg*500000" | bc -l)
#echo The average dihedral energy is $avg
##echo step number is $steps, time/steps is $avg, time per ns is $ns
#rm tmp
