#!/usr/bin/env bash
# This program takes a pdb as argument and generates a pore radius
# plot 

# help text
if [ $1 = "help" ]; then
    echo "This script, when provided with the pdb files as an argument, generates the hole data and a plot."
    exit 
fi

# abort if no arguments given
if [ -z "$1" ]; then
    echo "No arguments given"
    exit
fi

# check if the pdb/coordinate file exists 
if [ -f $1 ]
then
    echo "$1 exists"
else
    echo "Hey buddy, $1 doesn't exist"
    exit
fi

#          This part of the code would check if the file ended in .pdb
#if [ ${1:(-3)}=".pdb" ]; then
#    echo already has pdb label
#    exit
#fi
#exit

#echo -n "Enter a file name (if blank, will use pdb name): "
#read filename
if [ -z "$filename" ]; then
   # save only the main file name as the variable "name"
    filename=$(echo $1 | cut -f 1 -s -d ".")
fi

#take the file name from arguments for subsequent actions
name=$(echo $1 | cut -f 1 -s -d ".")
workingd=$(pwd)
cd ~/pores

# construct a hole input file and generate pore data
echo "coord $workingd/$name.pdb      ! co-ordinates in pdb format" > hole.inp
cat holetemplate >> hole.inp
hole < hole.inp > "tmp.txt"
rm hole.inp
egrep "mid-|sampled" "tmp.txt" | cut -c 13-36 > "$filename.txt"
rm tmp.txt
mv $filename.txt $workingd
cd $workingd

# move the hole data to a pycharm project, generate and save the plot 
$subhome/pore_plot $filename $file
