#!/usr/bin/env bash

ls *ns.pdb > pdbids.txt
cat pdbids.txt | cut -f 1 -s -d '_' > colorids2.txt
sed -i -e 's/indeprot/blue/g' colorids2.txt
sed -i -e 's/inoc/green/g' colorids2.txt
sed -i -e 's/in/orange/g' colorids2.txt
sed -i -e 's/outoc/red/g' colorids2.txt
sed -i -e 's/unbiased/blue/g' colorids2.txt
#sed -i -e 's/his/yellow/g' colorids2.txt
