#!/usr/bin/env bash
# This program should generate a job script from input

echo -n "Enter the output file name: "
read name

echo -n "Enter your wall time in whole hours: "
read walltime

cat ~/bin/jobs/template.pbs > $name.pbs
echo "#PBS -l walltime=$walltime:00:00" | cat >> $name.pbs
echo "#PBS -N $name" >> $name.pbs
cat ~/bin/jobs/template2.pbs >> $name.pbs
echo "namd2 +p 12 $name.log >& $name.log" | cat >> $name.pbs
