#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo -n "Enter the number of cores to test: "
    read cores
else
    cores=$1
fi

echo -n "Enter the output file name: "
read name
echo -n "Enter input file: "
read input 
if [ -f $input.xsc ]; then
    first=$(egrep "0 0 0" $input.xsc | cut -f 1 -s -d ' ')
else
    echo "Input file $input.xsc not found"
    exit
fi

cat ~/bin/scaling1.pbs > $name.$cores.pbs
echo "#PBS -l nodes=1:ppn=$cores,pmem=1gb" | cat >> $name.$cores.pbs
cat ~/bin/scaling2.pbs >> $name.$cores.pbs
#echo "cl" | cat >> namd$cores.pbs
echo "namd2 +p $cores $name.inp > $name.$cores.log" | cat >> $name.$cores.pbs

cat ~/bin/inptemplate1 > $name.inp
echo "outputname       $name;" | cat >> $name.inp
echo "set inputname    $input;" | cat >> $name.inp
echo "firsttimestep   $first;" | cat >> $name.inp
cat ~/bin/inptemplate2 >> $name.inp
echo "run        10000;" | cat >> $name.inp
