#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "No arguments given, please provide the name of the log file to average timing information from"
    exit
fi

egrep "TIMING:" $1 | cut -f 10 -d ' ' | cut -f 1 -d '/' > tmp
count=$(cat tmp | wc -l)
steps=$(egrep "TCL: Running" $1 | cut -f 4 -d ' ')

sum=0
for i in $(eval echo {1..$count});
do
    add=$(sed -n $i\p tmp)
    sum=$(echo "$sum + $add" | bc)
done
avg=$(echo "$sum / $count / 3600" | bc -l)
echo step number is $steps, time/steps is $avg
rm tmp
