#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Please provide psf and pdb inputs. If only coordinates are provided the standard psf will be used"
    exit
fi

cat $1 | cut -c 13-100 > tmp
count=$(cat tmp | wc -l)
rm tmp.bak
for i in $(eval echo {1..$((count))});
do
    search=$(sed -n $i\p tmp | cut -c 1-18)
    echo "Searching for $search"
    index=$(egrep "$search" ../step5_assembly.pdb | cut -c 1-13)
    echo "Writing $index to tmp.bak"
    sed -n $i\p tmp | sed s/^/"$index"/  >> tmp.bak
done
