#!/usr/bin/env bash
#transfer a working set of files to pylon5 for work

if [ -z $1 ]; then
  echo "Please enter the folder you would like to transfer to pylon5"
  exit
fi

echo $dir
destination=/pylon5/mc562gp/adamsa/
cp -r $1 $destination
