#!/usr/bin/env bash
#after a prodction run, transfer over the log, dcd, and most recent coor, vel, etc.

output=$1
dir=$(pwd | cut -f 5-6 -d '/')
echo $dir
destination=/pylon2/ct560hp/adamsa/$dir
cp $output.coor $destination
cp $output.vel $destination
cp $output.xsc $destination
cp $output.log $destination
cp $output.dcd $destination
