#!/usr/bin/env bash
# This portion of the abf script generates the conf file for the initial 2 ns of the abf simulation
# Please see abf for the start of the process 
# abf ---> win ---> abf_conf

out=win$1.conf

cat $templatehome/abfconftemplate1 > $out
echo "structure        ../$2" >> $out
echo "coordinates      win$1.pdb" >> $out
echo "set outputname        win$1" >> $out
if [ ${3: -4} == ".xsc" ]; then
  echo "extendedSystem ../$3" >> $out
else
  echo "extendedSystem ../$3.xsc" >> $out
fi
cat $templatehome/abfconftemplate2 >> $out
echo "colvarsConfig     win$1.in" >> $out
cat $templatehome/abfconftemplate3 >> $out
